export const products = [
  {
    id: "1",
    name: "Smartphone",
    shortDescription: "High-end smartphone with great camera",
    longDescription:
      "Meet the smartphone that redefines connectivity. With its advanced camera, powerful processor, and vibrant display, it seamlessly bridges work and leisure. Stay connected with cutting-edge 5G technology and enjoy a sleek design that fits perfectly in your hand.",
    price: 699.99,
    imageUrl: "http://127.0.0.1:3000/assets/smartphone.jpg",
    rating: 4.5,
    brand: "TechBrand",
    category: "Electronics",
    stock: 25,
    sku: "TB-SP-001",
    releaseDate: "2024-03-15",
  },
  {
    id: "2",
    name: "Laptop",
    shortDescription: "Powerful laptop for work and gaming",
    longDescription:
      "Experience unparalleled performance and portability with this state-of-the-art laptop. Whether you're a professional, student, or creative, this device is engineered to meet your demands. Enjoy ultra-fast processing, stunning graphics, and a lightweight design that lets you work and play wherever life takes you.",
    price: 1299.99,
    imageUrl: "http://127.0.0.1:3000/assets/laptop.jpg",
    rating: 4,
    brand: "ComputeX",
    category: "Computers",
    stock: 10,
    sku: "CX-LT-002",
    releaseDate: "2023-11-10",
  },
  {
    id: "3",
    name: "Headphones",
    shortDescription: "Noise-cancelling wireless headphones",
    longDescription:
      "Dive into a world of immersive sound with these premium headphones. Whether it’s music, calls, or gaming, they deliver crystal-clear audio and noise cancellation. Designed for comfort and durability, they are your perfect companion for long listening sessions.",
    price: 199.99,
    imageUrl: "http://127.0.0.1:3000/assets/headphones.jpg",
    rating: 3,
    brand: "SoundMax",
    category: "Audio",
    stock: 40,
    sku: "SM-HD-003",
    releaseDate: "2024-01-20",
  },
  {
    id: "4",
    name: "Watch",
    shortDescription: "A stylish and feature-packed timepiece.",
    longDescription:
      "Elevate your daily routine with this multi-functional smartwatch. Designed to complement your lifestyle, it offers fitness tracking, notifications, and customizable watch faces. Crafted with precision and style, it’s the perfect blend of technology and timeless design.",
    price: 249.99,
    imageUrl: "http://127.0.0.1:3000/assets/watch.jpg",
    rating: 2.5,
    brand: "TimeTech",
    category: "Wearables",
    stock: 15,
    sku: "TT-WT-004",
    releaseDate: "2024-05-05",
  },
  {
    id: "5",
    name: "Tablet",
    shortDescription: "Lightweight tablet for work and play",
    longDescription:
      "This tablet offers a perfect balance of performance and portability. Enjoy a vivid display, long battery life, and seamless multitasking for both productivity and entertainment.",
    price: 499.99,
    imageUrl: "http://127.0.0.1:3000/assets/tablet.jpeg",
    rating: 4.2,
    brand: "TabWorld",
    category: "Electronics",
    stock: 30,
    sku: "TW-TB-005",
    releaseDate: "2024-02-28",
  },
  {
    id: "6",
    name: "Bluetooth Speaker",
    shortDescription: "Portable speaker with deep bass",
    longDescription:
      "Take your music anywhere with this compact Bluetooth speaker. Delivers powerful sound, deep bass, and up to 12 hours of playtime on a single charge.",
    price: 89.99,
    imageUrl: "http://127.0.0.1:3000/assets/speaker.webp",
    rating: 3.8,
    brand: "BeatBox",
    category: "Audio",
    stock: 50,
    sku: "BB-SP-006",
    releaseDate: "2023-09-18",
  },
];
